### PR TITLE
return ipv4 address by hostname as string

### PR DESCRIPTION
**Pull request by jschanz**
receive the a-record ipv4 address by hostname as string to support mapping ip to host.address in synchronization rules. otherwise an error occurs, the arrays are not allowed as address

maybee this modifier needs a review and some code cleanup

> Diese Synchronisationsregel schlug bei der letzten Prüfung um 2017-04-04 13:20:49 fehl: Exception while syncing Icinga\Module\Director\Objects\IcingaHost localhost.localdomain: Storing icinga_host[localhost.localdomain] failed: Array to string conversion {array ( 'id' => '58', 'object_name' => 'localhost.localdomain', 'object_type' => 'object', 'disabled' => 'n', 'display_name' => 'localhost.localdomain', 'address' => array ( 0 => '192.168.2.250', ), 'address6' => NULL, 'check_command_id' => NULL, 'max_check_attempts' => NULL, 'check_period_id' => NULL, 'check_interval' => NULL, 'retry_interval' => NULL, 'enable_notifications' => NULL, 'enable_active_checks' => NULL, 'enable_passive_checks' => NULL, 'enable_event_handler' => NULL, 'enable_flapping' => NULL, 'enable_perfdata' => NULL, 'event_command_id' => NULL, 'flapping_threshold' => NULL, 'volatile' => NULL, 'zone_id' => NULL, 'command_endpoint_id' => NULL, 'notes' => 'virtuell', 'notes_url' => NULL, 'action_url' => NULL, 'icon_image' => NULL, 'icon_image_alt' => NULL, 'has_agent' => NULL, 'master_should_connect' => NULL, 'accept_config' => NULL, 'api_key' => NULL, )}

### CODE REVIEW

**Comment by ollybee** [comment]
This worked for me.

**Comment by Hrocc** [comment]
will this be merged in the master branch eventually @Thomas-Gelf ? It's kind of a showstopper when syncing hosts from active directory and you need the ip adress as a string. Thank you!

**Comment by lazyfrosch** [comment]
I see the point of wanting that kind of modifier.

What I'm not sure why `PropertyModifierGetHostByName` does not work for you. Which should lookup IPv4 address only by using [gethostbyname()](http://de2.php.net/manual/en/function.gethostbyname.php)

From what I understand, people asked for a better option to retrieve single IPv6 addresses, which is only possible with [dns_get_record](http://de2.php.net/manual/en/function.dns-get-record.php)

I'd update `PropertyModifierDnsRecords` to be able to retrieve a single value, and optionally fail on multiple results.

**Comment by Hrocc** [comment]
@lazyfrosch `PropertyModifierGetHostByName`  does work indeed - my fault, for ipv4 thats fine.

**Comment by lazyfrosch** [comment]
@jschanz do we really need this PR, does `PropertyModifierGetHostByName` not work for you?

**Pull request closed without merging**
