### PR TITLE
fixes #2393 clusterzone check is not a plugincheck

### LINKED ISSUE #2393: IcingaDirector can't create ClusterZoneCheck
https://github.com/Icinga/icingaweb2-module-director/blob/302c9b645d901567df5433657487701627396d0d/library/Director/Objects/IcingaCommand.php#L63
should be 
        'ClusterZoneCheck' => 'cluster-zone-check-command',

thanks for this great software and

best regard
nicolas

### PR DESCRIPTION
**Pull request by moreamazingnick**

### CODE REVIEW

**Comment by lippserd** [comment]
@raviks789 please check PR.

**Comment by moreamazingnick** [comment]
Somehow it works without the change since 1.10

**Comment by lippserd** [comment]
> Somehow it works without the change since 1.10

Thanks for the reply. But I think it should still be corrected to `cluster-zone-check-command`.

**Review by raviks789 — COMMENTED** [review]
LGTM

**Pull request merged**
