### PR TITLE
Update testing scripts and settings

### PR DESCRIPTION
**Pull request by lazyfrosch**
Not only for travis, but also for local use.

This is similar to how other modules handle it right now:
* icingaweb2-module-businessprocess
* icingaweb2-module-eventdb

### CODE REVIEW

**Comment by lazyfrosch** [comment]
This now also limits the branches build by Travis.

This "requires" using PRs for everything besides from testing:
* master
* next
* support/*
* tags

**Comment by lazyfrosch** [comment]
@Thomas-Gelf ready 4 merge / review / refactor :tongue:

**Comment by Thomas-Gelf** [comment]
Looks good to me, @lazyfrosch. Just a few questions:
* out of curiosity, what's the main reason for limiting branches for Travis? And, did you intentionally leave feature/* away?
* is it possible to have *.php in the phpcs XML file for all PHP files in the root directory?

**Comment by lazyfrosch** [comment]
Hmm seems like my mail client swallowed the reply...

> out of curiosity, what's the main reason for limiting branches for Travis? And, did you intentionally leave feature/* away?

Travis by default builds against all branches you push to, since PR are the recommended way to merge branches, I only included our main branches and tags.

> is it possible to have *.php in the phpcs XML file for all PHP files in the root directory?

Unfortunatly phpcs.xml can't do wildcards, I tried :wink:

**Pull request merged**
