### PR TITLE
update requirements to properly reflect dependencies for current icingaweb2

### PR DESCRIPTION
**Pull request by fireba11**
Info:
Versions are taken from missing dependancy messages from director 1.8.1

### CODE REVIEW

**Comment by fireba11** [comment]
meh.
mail should be okay now, how do i get the bot to re-check?
apparently a cla is required, where is the how-to for that? can't find anything.

feel free to just make a proper pull request with that change and drop this one ...

**Comment by nilmerg** [comment]
@cla-bot check

**Comment by icingaadmin** [comment]
@cla-bot check

**Comment by Thomas-Gelf** [comment]
Thank you for this pull request! It hasn't been merged as an earlier one (#2360) already addressed this at the time being

**Pull request closed without merging**
