### PR TITLE
Feature 11332 support dependencies 20161118

### PR DESCRIPTION
**Pull request by mdetrano**
This is an update to the dependency support feature branch.  This should merge more smoothly with the current master branch.  Updated to use newer methods to present nested Apply rules on the form, including updates to the database schema for Dependency objects (to follow what was changed for similar objects).  Created dashlet object for the Director Dashboard, and other small fixes to get this feature implementation up-to-date.

### CODE REVIEW

**Comment by spacefreak86** [comment]
Hi there,

The ability to define dependencies is essential for the upgrade our installation.
Currently, we are running iCinga 1 with NConf to generate the configuration.

We would like to upgrade to iCinga 2 with icingaweb2-module-director, but as long as
we are not able to define dependencies within the director module, it is not possible.

**Comment by TheFlyingCorpse** [comment]
There are now conflicts in merge.

**Comment by mdetrano** [comment]
Branch should now merge cleanly with latest master branch from upstream Director project.

**Comment by Shadowghost** [comment]
Any news on this @mdetrano? Still planning to merge it (after fixing the merge conflicts)?

**Comment by mdetrano** [comment]
Will close this pull request and will try again with a new, clean branch to implement this feature.

**Pull request closed without merging**
