### PR TITLE
schema/150: Add constraint from user to period

### LINKED ISSUE #1578: Deployment failed with "Failed to load icinga_timeperiod "" (IcingaObject.php:329)"
## Current Behavior
I've deleted two old time zones and the deployment afterwards failed with:
Failed to load icinga_timeperiod "" (IcingaObject.php:329)

## Your Environment

* Director version (System - About): master
* Icinga Web 2 version and modules (System - About): 2.6
* Icinga 2 version (`icinga2 --version`): r2.9.0-1
* Operating System and version: Ubuntu 16.04
psql (PostgreSQL) 9.5.13

### PR DESCRIPTION
**Pull request by lazyfrosch**
* [ ] Use other UPDATE query from https://github.com/Icinga/icingaweb2-module-director/pull/1627#issuecomment-418799911

fixes #1578

### CODE REVIEW

**Comment by Thomas-Gelf** [comment]
Thanks... but... this shows still the same query?

**Comment by lazyfrosch** [comment]
Yes still WIP, I have to test the query still

**Comment by Thomas-Gelf** [comment]
7317 image_0f65063b

**Comment by lazyfrosch** [comment]
Tested with Postgres 10.9 and MariaDB 10.3.9

**Comment by lazyfrosch** [comment]
Backported to `support/1.5`

**Pull request merged**
