### PR TITLE
Fix Variable ICINGAWEB2_MODULES in Bash Excample

### PR DESCRIPTION
**Pull request by igor-sweet**
Changed ICINGAWEB_MODULES to ICINGAWEB2_MODULES

### CODE REVIEW

**Comment by Thomas-Gelf** [comment]
Could you please commit this with a real name or tell me such so that I can fake it for you? Our policy does not allow commits with nick names only.

**Comment by Thomas-Gelf** [comment]
ping @igor-sweet

**Comment by Thomas-Gelf** [comment]
This has been fixed.

**Comment by igor-sweet** [comment]
Thanks! 

Sorry for the delay. The "nickname" is the only one to find on the net. Maybe it's worth to get it in the passport as "künstlername"

Am 11. Oktober 2016 14:49:02 MESZ, schrieb Thomas Gelf <notifications@github.com>:

**Pull request closed without merging**
