### PR TITLE
fix wrong type casting

### PR DESCRIPTION
**Pull request by cmaile**
Remove wrong type casting:

ts_last_attempt: 2022-12-07 21:24:53
ts_last_attempt (with type casting to int): 2022

### CODE REVIEW

**Comment by cmaile** [comment]
Signed the CLA.

**Comment by cmaile** [comment]
Recheck

**Comment by Thomas-Gelf** [comment]
Merged, thank you!

**Comment by bobapple** [comment]
@cla-bot check

**Pull request merged**
