### PR TITLE
Sync: Respect the fields used in filter_expression of the SyncRule

### LINKED ISSUE #1130: Filter expression on SyncRule only works when field is used in column filter or properties
The fix in #876 doesn't fix all issues regarding that.

Here is a crude yaml example:

```yaml
rules:
- name: test
  filter_expression: field=*
  properties:
  - source: testdata
    source: ip
    destination: address
```

#876 only fixed that filters on individual properties are taken into account, but the columns used in filter_expression on the rule itself are not taken into account.

/cc @mkayontour @tobiasvdk

### LINKED ISSUE #1141: ImportSource with imports can not be deleted on PostgreSQL
You can not delete ImportSources that had an Import on PostgreSQL.

## Expected Behavior

ImportSource should cascade to deleting all ImportRun in the database.

Works on MySQL.

## Current Behavior

Breaks because of foreign key restriction.

```
SQLSTATE[23503]: Foreign key violation: 7 ERROR: update or delete on table "import_source" violates foreign key constraint "import_run_source" on table "import_run"
DETAIL: Key (id)=(2) is still referenced from table "import_run"., query was: DELETE FROM import_source WHERE (id = '2')
```

## Possible Solution

Update the foreign key constraint in a similar way than MySQL.

## Your Environment

* Director version (System - About): master - 59eda8f9c41f4686a11adc695290700ef54f5c57
* Icinga Web 2 version and modules (System - About): 2.4.1

### PR DESCRIPTION
**Pull request by lazyfrosch**
So that you can filter by fields not used in properties, or in property filters.

fixes #1130
refs #876 

Also fixes #1141 for tests

### CODE REVIEW

**Comment by lazyfrosch** [comment]
**NOTE:** Currently untested, lacking a proper test environment.

Please test and give feedback @mkayontour

**Comment by lazyfrosch** [comment]
@mkayontour please also test if this works with your multi-level column `guest.ipAddress`!

**Comment by Thomas-Gelf** [comment]
@lazyfrosch: thank you, this was indeed missing. I also didn't try it out, but it looks good to me.

**Comment by Thomas-Gelf** [comment]
Ping @mkayontour

**Comment by lazyfrosch** [comment]
The behavior intended to fix should work.

@Thomas-Gelf I've added a test for Sync, please review. It tests for basic Import/Sync behavior and filters. Still extendable :laughing:

**Comment by lazyfrosch** [comment]
Fixed a small mistake for PostgreSQL

**Comment by lazyfrosch** [comment]
Seems like I have to take a closer look on testing with PostgreSQL

**Comment by lazyfrosch** [comment]
PostgreSQL tests fail because of #1141

**Comment by lazyfrosch** [comment]
@Thomas-Gelf ready 4 merge / review / refactor :tongue:

**Comment by Thomas-Gelf** [comment]
@lazyfrosch: well done, thank you!

**Pull request merged**
