### PR TITLE
fix error when trying to create scheduled_downtime via api

### LINKED ISSUE #1879: Error modifying Scheduled Downtime Object with PUT via REST API
## Expected Behavior

When attempting to modify a Scheduled Downtime object using the REST API, and a PUT action, the object should be updated.
 

## Current Behavior

An error is returned:

> {"status":"error","message":"Uncaught Error: Class 'Icinga\\Module\\Director\\Objects\\IcingaScheduled-downtime' not found ...

a POST or GET to the same URI endpoint ("...director/scheduled-downtime")  works correctly.

## Possible Solution

I think the fix is simple.  In ..library/Director/Objects/IcingaObject.php , line 2561 or so in the classByType method, this line:

`} elseif ($type === 'scheduled_downtime') {`

should be
`} elseif ($type === 'scheduled-downtime') {`

## Steps to Reproduce (for bugs)

Create a scheduled downtime object.

Use a curl GET to copy the json data:

`curl -XGET -k -H 'Accept: application/json' -u '{user}:{pass}' https://localhost/icingaweb2/director/scheduled-downtime?name=test_downtime > downtime.dat`

try to "PUT" the data back to the object:

curl -XPUT -k -H 'Accept: application/json' -u '{user:pass}' https://localhost/icingaweb2/director/scheduled-downtime?name=test_downtime -d @downtime.dat

## Your Environment

* Director version (System - About): master (2019-May-22)
* Icinga Web 2 version and modules (System - About): 2.6.3
* Icinga 2 version (`icinga2 --version`):
* Operating System and version:
* Webserver, PHP versions:

### PR DESCRIPTION
**Pull request by rndmh3ro**
fixes #1879.

### CODE REVIEW

**Comment by rndmh3ro** [comment]
Any reason this cannot be merged?

**Comment by lazyfrosch** [comment]
@Thomas-Gelf can we merge that?

**Comment by rndmh3ro** [comment]
Half a year is gone by... Any chance this will be merged?

**Comment by Thomas-Gelf** [comment]
I'll merge both variants, just to be on the safe side :see_no_evil:

**Comment by Thomas-Gelf** [comment]
Has slightly been modified and merged with fed74eb

**Pull request closed without merging**
