### PR TITLE
Add php action workflow

### PR DESCRIPTION
**Pull request by nilmerg**
Unit tests are still missing

### CODE REVIEW

**Comment by Thomas-Gelf** [comment]
@nilmerg: thanks! Is this ready to be merged?

**Comment by Thomas-Gelf** [comment]
I would either immediately merge it or otherwise (in case this is still a work in progress) cherry-pick just the indentation fix

**Comment by nilmerg** [comment]
These are only the style and lint tests. I planned to also add unit tests to this and drop travis. But if you want to merge it already, feel free to do it.

**Comment by nilmerg** [comment]
Some tests fail. But they do that locally as well. So :man_shrugging:

**Pull request merged**
