### PR TITLE
Add Servicegroups directly to Services

### PR DESCRIPTION
**Pull request by dgoetz**
As discussed in #619

### CODE REVIEW

**Comment by Damoun** [comment]
Hi,

What's the state of this PR ? I just experienced the need for this feature :D

**Comment by Thomas-Gelf** [comment]
Reason for not merging this was:

* it should not be up to the end user to decide which group a Service belongs to
* in nearly all the cases this should be pretty clear once you define your Service template
* in case it isn't, you're probably doing templates wrong
* examples might be legacy ugliness like one generic nrpe template while having all the details in your Services - like in the linked discussion
* service groups might become a security feature, like host groups. Once restricted, you're no longer allowed to touch them

I delayed as I wasn't yet sure about all of it's implications and honestly didn't invest time to reflect it. It's now in the master, so what - I wasn't strictly against it. Still, I'm very curious to learn about other real-world use-cases for this feature. Is there anything else, apart from the mentioned NRPE-BS?

ping @dgoetz, @lazyfrosch.

**Comment by lazyfrosch** [comment]
In my view I want to support the basic features of Icinga 2.

E.g. whats the point of being able to sync a param, but not being able to set in the UI.

In terms of restrictions for "users" this has to be addressed in a different way...

**Comment by Thomas-Gelf** [comment]
Sync is an Admin-only feature, Templates are Admin-only features, single Services are not. Services should be as lean as possible and are to be seen as an "End User Feature". Mapping every single parameter in every place was never the goal for the Director - and it should never be. Otherwise it should better have been a web-based config file editor.

Looking forward to learning about real-world use-cases for this feature.

Thanks,
Thomas

**Comment by Thomas-Gelf** [comment]
Valid points. But. In my naive view of the world, "Application" is a property - and should be a Custom Variable. Same goes true for "High Priority". Now if someone in addition to those flags wants to also have Service Groups, they can be assigned via Apply Rules based on those properties.

Thoughts?

**Pull request merged**
