### PR TITLE
schema/150: Add constraint from user to period

### LINKED ISSUE #1578: Deployment failed with "Failed to load icinga_timeperiod "" (IcingaObject.php:329)"
## Current Behavior
I've deleted two old time zones and the deployment afterwards failed with:
Failed to load icinga_timeperiod "" (IcingaObject.php:329)

## Your Environment

* Director version (System - About): master
* Icinga Web 2 version and modules (System - About): 2.6
* Icinga 2 version (`icinga2 --version`): r2.9.0-1
* Operating System and version: Ubuntu 16.04
psql (PostgreSQL) 9.5.13

### PR DESCRIPTION
**Pull request by lazyfrosch**
fixes #1578

### CODE REVIEW

**Comment by lazyfrosch** [comment]
We could also include this in 1.5.2...

**Comment by Thomas-Gelf** [comment]
@lazyfrosch: sorry, I had to revert this in fbef886.

Please use a query like:

```sql
UPDATE icinga_user u
  SET period_id = NULL
  WHERE NOT EXISTS (
    SELECT id FROM icinga_timeperiod
    WHERE id = u.period_id
  ) AND u.period_id IS NOT NULL;
```

**Comment by Thomas-Gelf** [comment]
@lazyfrosch: once fixed, v1.5.2 is fine for me.

**Comment by lazyfrosch** [comment]
New PR then is #1628

**Pull request merged**
