### PR TITLE
Fix typo in SNMP Data Fields example documentation

### PR DESCRIPTION
**Pull request by sam-banks**
Hi,

I was reading the Icinga Director documentation and spotted a typo in the [Data Fields example: SNMP](https://icinga.com/docs/icinga-director/latest/doc/16-Fields-example-SNMP/) page. I've included a patch to fix the typo.

Thanks!

### CODE REVIEW

**Comment by sam-banks** [comment]
I've signed and submitted the CLA, can you please verify?

**Comment by lippserd** [comment]
@sam-banks Thank you for taking the time to submit the PR.

@cla-bot check

**Review by lippserd — APPROVED** [review]

**Comment by sam-banks** [comment]
Thanks for accepting the changes @lippserd. Is there anything further required on my end? Should this issue remain open?

**Comment by lippserd** [comment]
> Thanks for accepting the changes @lippserd. Is there anything further required on my end? Should this issue remain open?

Nope, I will just merge it.

**Comment by sam-banks** [comment]
Thanks again :)

**Pull request merged**
