### PR TITLE
feature/notification_interval

### PR DESCRIPTION
**Pull request by n0braist**
it would be great if there would be the possibility using a custom host or service variable instead of a fixed value in the notifation definitions for the field notification_interval.
The background is, that so it would be possible, that one 'global' notification rule can be used with different renotifications instead of recreating and not assigned rules for a few individual notifications.

### CODE REVIEW

**Comment by widhalmt** [comment]
ref/NC/603133

**Comment by lazyfrosch** [comment]
looks like this PR has the wrong branch set to compare.

We won't merge `support/1.6` into `master`.

Is this meant as issue, or do you have a branch with changes somewhere I can't see?

**Comment by n0braist** [comment]
Hi,

vermutlich war ich einfach nur zu dusselig es „normalen“ feature-request einzutüten….

Grüße Stefan

**Comment by lazyfrosch** [comment]
Closing this PR then :wink:

**Pull request closed without merging**
